### ISSUE TITLE
Unbundled development

### ISSUE THREAD

**Issue by gunar** [react-cosmos/rfcs#18]
Hi,

Tools like [snowpack](https://github.com/snowpackjs/snowpack) and [vite](https://github.com/vitejs/vite) make for a much faster feedback loop as they don't bundle code while on development. I'd love if react-cosmos would be made compatible with these tools. Pardon me if this is possible already with some sort of specific configuration.

Thanks in advance.

PS: react-comsos is great, thank you for your work!

**Comment by ovidiuch** [comment]
Hi @gunar,

I'd love to see this happen. How willing are you to experiment with this? 😅

I don't think it's been done before, but it's definitely possible. There are Parcel and Browserify integrations on the Cosmos org, but unfortunately they're for an older version of Cosmos.

[The current webpack entry point](https://github.com/react-cosmos/react-cosmos/blob/e92f1ecbce529af4b4706172b7e5aae15823ff1e/packages/react-cosmos/src/dom/index.tsx) is a good starting point for discovering how to Cosmos parts come together. [The React Native entry point](https://github.com/react-cosmos/react-cosmos/blob/master/packages/react-cosmos/src/native.tsx) is also interesting to check out to see the difference, and because it doesn't work with webpack. The Cosmos UI ("Playground") is webpack agnostic, and on the server side webpack is internally abstracted as a plugin.

I'm more than happy to offer answers, even jump into short calls if needed, for anyone willing to take on this challenge.

**Comment by tsanyqudsi** [comment]
I don't know if this came too late. But i've managed to make it work with vite ( kinda copy it from  https://github.com/kazuma1989/react-cosmos-with-vite ) for the most part.

And putting aside that i have to run both vite and react-cosmos server at the same time. I don't see any disadvantage.

my suggestion is to split the builder into different package perhaps ? For example when you run react-cosmos, instead of just doing `cosmos`, you have to write `cosmos --builder='vite'` or `cosmos --builder='webpack5'`

This way, React Cosmos might be able to withstand any custom builder in the future.

**Comment by ovidiuch** [comment]
> my suggestion is to split the builder into different package perhaps ? For example when you run react-cosmos, instead of just doing `cosmos`, you have to write `cosmos --builder='vite'` or `cosmos --builder='webpack5'`

Indeed this is the dream. Cosmos used to have a separate package for webpack initially, which was later merged with the core Cosmos package because everybody in the React community was using webpack back then and it simplified things. But the long term vision is what you're pointing out, to install separate Cosmos plugin packages for specific bundlers.

**Comment by ovidiuch** [comment]
Cosmos now has `react-cosmos-plugin-vite` plugin 😇.
